spring:
  application:
    name: iot-cmp-services-sms
  main:
    banner-mode: "off"
  profiles:
    active: "default"

server:
  port: 9005

#Actuator
management:
  server:
    port: 9006  # different port for actuator check
  endpoints:
    web:
      exposure:
        include: health,info   # only exposes these endpoints
  endpoint:
    health:
      show-details: always

ioto:
  cmp:
    service:
      sms:
        smpp:
          host: 127.0.0.1
          port: 2775
          system-id: smppclient1
          password: password
          system-type: cp
          service-type: CMT
          reconnect-delay-ms: 5000
          source-number: ioto
          source-ton: INTERNATIONAL
          source-npi: ISDN
          dest-ton: INTERNATIONAL
          dest-npi: ISDN





